### ISSUE TITLE
Refactoring 

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/ctp7_modules#25]
### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)
- [x] Bad coding style
## Expected Behavior

All the duplicated code has to be moved to dedicated methods and called as appropriate
## Current Behavior

There're number of code snippets duplicated - see e.g. https://github.com/cms-gem-daq-project/ctp7_modules/pull/17

**Comment by bdorney** [comment]
Based on some discussion we had over email I would propose additional refactoring:

# Coding Style
We have a somewhat split way of coding.  We have functions defined and implemented in header files and then the source file only has the `extern C{ ... }` bit where the rpc module is registered (example `optohybrid.h` and `optohybrid.cc`).  In other cases no header file exists and everything is done in a source file (example `calibration_scans.cc`).

This is frustrating since if one makes a change to a header file but not the source file a `make clean` is required for a recompile while the source file may never change since the implementation is actually being presently done in the header file.  Also a new developer may find it non-intuitive.

Just my two cents here. 

**@mexanick:this is already implemented, but requires testing which I have requested, but never got a reply**

# Coding for Automatic Documentation
The ctp7_modules documentation that was prepared by @mexanick has some functions that do not have any explanation as to what their input parameters are.  I understood the document was autogenerated by `doxygen` so the explanation of the input parameters needs to go into the code.

How is `doxygen` grabbing this information?  E.g. how should we put comments such that `doxygen` grabs it?

**@mexanick:Please consider looking at the [*doxygen manual*](https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)**

I guess:

```
void myFunc(Type Arg1, Type Arg2, ...){
   \*
   Arg1 - description for Arg1
               with further Arg1 description spanning multiple lines.
   Arg2 - description for Arg2
   *\
} 
```

## Statements for Clarifying v2b Only Methods
The following methods are only for working with `v2b` electronics (maybe more) but this is not specified in the code/documentation:

- `configureScanModuleLocal(…)` section 8.1.2.7
- `getUltraScanResults(…)` section 8.1.2.9
- `getUltraScanResultsLocal(…)` section 8.1.2.10
- `loadVT1Local(…)` section 8.1.2.14
- `printScanConfigurationLocal(…)` Section 8.1.2.16
- `startScanModuleLocal(…)` Section 8.1.2.20

There is also `LoadTRIMDAC(...)` and `LoadTRIMDACLocal(...)`.  They also are right now only for the  `v2b` electronics but since v3 also has trim settings one could see them updated at some point in time...?

**@mexanick:the documentation I've sent is a first attempt to create it. Of course it is far from perfect and should be refined. However in order to avoid huge PRs which are hard to review, I would postpone this to the time after the main changes will be merged.**
## "Bad" Documentation
The comments in the code that I wrote for `ttcGenToggleLocal(...)`  are somewhat inaccurate-ish.  For v3 case it reads:

> v3  electronics: enable = true (false) ignore (take) ttc commands from backplane for this AMC

While this is true it is misleading because it is actually turning on the TTC GENERATOR in the CTP7 FW; which does disable ttc commands from the backplane but will also start “local” TTC commands!.  

The same applies to `ttcGenConfLocal(...)` since the comments in the code were just copy/pastes.

**@mexanick:after the refactoring PR will be merged you're welcome to provide the changes and clarifications to the documentation**
# Moving Functions Around
## Moving to `amc.cpp`
I would suggest we move some functions from `calibration_scans.cc` (I noticed in the refactoring PR this file extension was changed to `*.cpp` which is no problem just want to avoid naming confusion) to `amc.cpp` since they seem more appropriate there.  

**@mexanick:CPP extension has been used from the beginning of the this repository**


Specifically:

- `dacMonConf(...)` and `dacMonConfLocal(...)` since this configures the `VFAT_DAQ_MONITOR` in the CTP7 FW.

- `ttcGenToggle(...)` and `ttcGenToggleLocal(...)` since this configures the TTC Generator.

- `fw_version_check()` since this checks the AMC FW version

**@mexanick:I'm not in favor of the changes proposed above since the will lead to additional cross-dependencies**

## Moving to `vfat3.cpp`
I would suggest to move the following methods out of `calibration_scans.cpp` and into `vfat3.cpp`:

- `applyChanMask(…)`
- `setSingleChanMask(…)`

And their `Local` counterparts.  Additionally It may be wise to move from `optohybrid.h` the following:

- `stopCalPulse2AllChannels(...)`
- `stopCalPulse2AllChannelsLocal(...)`

This way we keep all `vfat3` channel register actions in one file.

## Making a `vfat2.cpp` 

**@mexanick:We want the host PC software to be agnostic of the HW/FW version used. This proposal goes against our initial goal which we have been discussing many times**
Presently the current implementation of:

- `biasAllVFATsLocal(...)`
- `configureVFATs(…)`

Is specific to VFAT2.  Perhaps we should migrate these, and their Local/Non-Local counterparts, to a `vfat2.cpp` block along with the following from `optohybrid.cc`:

- `setAllVFATsToRunModeLocal(...)`
- `SetAllVFATsToSleepModeLocal(...)`
- `loadVT1Local(...)`
- `loadVT1(...)`
- `LoadTRIMDACLocal(...)`
- `LoadTRIMDAC(...)`

Although maybe we should think about the issue of configuring the electronics further before doing this, e.g. how do we use databases, how do we do the block transactions...etc...then maybe there could be some changes to the implementation and add more vfat3 functionality.  Although I would still be in favor, for maintainability and readability reasons, to separate vfat2 and vfat3 behavior into separate functions.

**Comment by mexanick** [comment]
Thank you for re-raising the issue above. Certain work has been already done already. I will edit your  comment as the quotation mechanism isn't perfect on github and I believe inline answers will be better in this case
