### ISSUE TITLE
Bug Report: `applyMask(...)` is not used correctly when scanning DACs in higher bit positions in `dacScanLocal(...)`

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/ctp7_modules#59]
## Brief summary of issue

There's an issue with the DAC scans when attempting to scan higher bits of global control registers due to writing address instead of node, mask applied incorrectly.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Current Behavior

When performing a DAC scan on those DAC's that occupy higher bits of a global control register (e.g. `CFG_BIAS_PRE_I_BLCC` which is bits [13:8]` of `GBL_CFG_BIAS_2`) the value applied in `dacScanLocal(...)`:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/e1d9d0c52a9bd5ffae96e99706ffd12b6ba2809b/src/calibration_routines.cpp#L1478-L1479

Is not correct, e.g. if logging is used to investigate what the value applied when using `applyMask`:

```
Oct 17 07:03:00 eagle64 local0.info rpcsvc[30814]: calibration_routines.dacScanMultiLink: dac Val 0x3f with regMask 0x3f00 and applied value (after Mask) 0x0
```
Instead of `0x3f` written to bits [13:8] a value of `0x0` is written which is incorrect.  Instead of [applyMask](https://github.com/cms-gem-daq-project/ctp7_modules/blob/e1d9d0c52a9bd5ffae96e99706ffd12b6ba2809b/src/utils.cpp#L236-L249) perhaps a bit shift needs to be used instead.

### Steps to Reproduce (for bugs)

1. `run_scans.py dacScanV3 eagle64 0x3 3`

## Possible Solution (for bugs)

The DAC scans are *very* fast as is (~1 minute max) so instead of trying to use the raw address when performing the DAC scan using the node name would be more reliable, e.g. instead of:

```C++
writeRawAddress(regAddr[vfatN], applyMask(dacVal, regMask[vfatN]), la->response);
```

We use:

```C++
writeReg(la, strDacReg, dacVal);
```

Where `strDacReg` is the full node name of the DAC of interest.

## Context (for feature requests)

Prevents DAC scans on higher bits of global control registers.  Prevents configuring the chip properly.

## Your Environment

* Version used: `e5a6b0e87c8584b2466933b2af264cb3f320e7ed`

**Comment by jsturdy** [comment]
`writeRawAddress` is a single transaction but this code is trying to use it as though it were an `RMW` (`read-modify-write`) transaction.
If you wanted to use this method (it seems that you don't in this case, but potentially you do somewhere else) you need the inverse of `applyMask`, i.e., you need to read the current register value, modify the bits you want to change, and then write this full value with the `writeRawAddress` function.
This is already what you get when you write by node name, minus the cost of the lookup:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/e1d9d0c52a9bd5ffae96e99706ffd12b6ba2809b/src/utils.cpp#L302-L322

So that part of `writeReg` could be stripped out into a new function, and then used both in `writeReg` as well as on its own, e.g., a new function `writeMaskedAddress(addr, value, mask)`
